
# This is a basic workflow to help you get started with Actions
name: CALLER

# Controls when the workflow will run
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    uses: muzahm01/action_playground/.github/workflows/blank.yml@main
